services:
  db:
    image: mysql:8.0
    container_name: imageapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: imageappdatabase
      MYSQL_USER: imageuser
      MYSQL_PASSWORD: imagepass
    ports:
      - "3310:3306"
    command:
      - "mysqld"
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: imageapp-api
    working_dir: /app
    command: >
      bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers"
    # host'a map ETMİYORUZ; sadece compose ağına açıyoruz
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - MEDIA_ROOT=/data
    volumes:
      - ./backend:/app
      - ./data:/data  # MEDIA_ROOT=/data ile eşleşir
    ports:
    - "8000:8000"

  frontend:
    build: 
      context: ./frontend
    container_name: imageapp-frontend
    command: ["npm","run","dev","--","--host"]
    expose:
      - "5173"
    volumes:
      - ./frontend/image-app:/app/image-app
      - /app/image-app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=/api
    depends_on:
      - api
    ports:
    - "5173:5173"

  proxy:
    image: nginx:alpine
    container_name: imageapp-proxy
    depends_on:
      - api
      - frontend
    ports:
      - "8080:80"
    # Nginx konfigini buraya mount ediyoruz
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
