apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: imageapp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_DATABASE: "imageappdatabase"
  MYSQL_USER: "imageuser"
  MYSQL_PASSWORD: "imagepass"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: imageapp
data:
  VITE_API_BASE_URL: "/api"
  MEDIA_ROOT: "/data"
